<select name="wp_hitpay_options[currency]" id="currency" style="" class="wc-enhanced-select select2-hidden-accessible enhanced" tabindex="-1" aria-hidden="true">
		<option value="AED" <?php selected( $currency, 'AED' ); ?>>United Arab Emirates dirham (د.إ) — AED</option>
		<option value="AFN" <?php selected( $currency, 'AFN' ); ?>>Afghan afghani (؋) — AFN</option>
		<option value="ALL" <?php selected( $currency, 'ALL' ); ?>>Albanian lek (L) — ALL</option>
		<option value="AMD" <?php selected( $currency, 'AMD' ); ?>>Armenian dram (AMD) — AMD</option>
		<option value="ANG" <?php selected( $currency, 'ANG' ); ?>>Netherlands Antillean guilder (ƒ) — ANG</option>
		<option value="AOA" <?php selected( $currency, 'AOA' ); ?>>Angolan kwanza (Kz) — AOA</option>
		<option value="ARS" <?php selected( $currency, 'ARS' ); ?>>Argentine peso ($) — ARS</option>
		<option value="AUD" <?php selected( $currency, 'AUD' ); ?>>Australian dollar ($) — AUD</option>
		<option value="AWG" <?php selected( $currency, 'AWG' ); ?>>Aruban florin (Afl.) — AWG</option>
		<option value="AZN" <?php selected( $currency, 'AZN' ); ?>>Azerbaijani manat (₼) — AZN</option>
		<option value="BAM" <?php selected( $currency, 'BAM' ); ?>>Bosnia and Herzegovina convertible mark (KM) — BAM</option>
		<option value="BBD" <?php selected( $currency, 'BBD' ); ?>>Barbadian dollar ($) — BBD</option>
		<option value="BDT" <?php selected( $currency, 'BDT' ); ?>>Bangladeshi taka (৳&nbsp;) — BDT</option>
		<option value="BGN" <?php selected( $currency, 'BGN' ); ?>>Bulgarian lev (лв.) — BGN</option>
		<option value="BHD" <?php selected( $currency, 'BHD' ); ?>>Bahraini dinar (.د.ب) — BHD</option>
		<option value="BIF" <?php selected( $currency, 'BIF' ); ?>>Burundian franc (Fr) — BIF</option>
		<option value="BMD" <?php selected( $currency, 'BMD' ); ?>>Bermudian dollar ($) — BMD</option>
		<option value="BND" <?php selected( $currency, 'BND' ); ?>>Brunei dollar ($) — BND</option>
		<option value="BOB" <?php selected( $currency, 'BOB' ); ?>>Bolivian boliviano (Bs.) — BOB</option>
		<option value="BRL" <?php selected( $currency, 'BRL' ); ?>>Brazilian real (R$) — BRL</option>
		<option value="BSD" <?php selected( $currency, 'BSD' ); ?>>Bahamian dollar ($) — BSD</option>
		<option value="BTC" <?php selected( $currency, 'BTC' ); ?>>Bitcoin (฿) — BTC</option>
		<option value="BTN" <?php selected( $currency, 'BTN' ); ?>>Bhutanese ngultrum (Nu.) — BTN</option>
		<option value="BWP" <?php selected( $currency, 'BWP' ); ?>>Botswana pula (P) — BWP</option>
		<option value="BYR" <?php selected( $currency, 'BYR' ); ?>>Belarusian ruble (old) (Br) — BYR</option>
		<option value="BYN" <?php selected( $currency, 'BYN' ); ?>>Belarusian ruble (Br) — BYN</option>
		<option value="BZD" <?php selected( $currency, 'BZD' ); ?>>Belize dollar ($) — BZD</option>
		<option value="CAD" <?php selected( $currency, 'CAD' ); ?>>Canadian dollar ($) — CAD</option>
		<option value="CDF" <?php selected( $currency, 'CDF' ); ?>>Congolese franc (Fr) — CDF</option>
		<option value="CHF" <?php selected( $currency, 'CHF' ); ?>>Swiss franc (CHF) — CHF</option>
		<option value="CLP" <?php selected( $currency, 'CLP' ); ?>>Chilean peso ($) — CLP</option>
		<option value="CNY" <?php selected( $currency, 'CNY' ); ?>>Chinese yuan (¥) — CNY</option>
		<option value="COP" <?php selected( $currency, 'COP' ); ?>>Colombian peso ($) — COP</option>
		<option value="CRC" <?php selected( $currency, 'CRC' ); ?>>Costa Rican colón (₡) — CRC</option>
		<option value="CUC" <?php selected( $currency, 'CUC' ); ?>>Cuban convertible peso ($) — CUC</option>
		<option value="CUP" <?php selected( $currency, 'CUP' ); ?>>Cuban peso ($) — CUP</option>
		<option value="CVE" <?php selected( $currency, 'CVE' ); ?>>Cape Verdean escudo ($) — CVE</option>
		<option value="CZK" <?php selected( $currency, 'CZK' ); ?>>Czech koruna (Kč) — CZK</option>
		<option value="DJF" <?php selected( $currency, 'DJF' ); ?>>Djiboutian franc (Fr) — DJF</option>
		<option value="DKK" <?php selected( $currency, 'DKK' ); ?>>Danish krone (kr.) — DKK</option>
		<option value="DOP" <?php selected( $currency, 'DOP' ); ?>>Dominican peso (RD$) — DOP</option>
		<option value="DZD" <?php selected( $currency, 'DZD' ); ?>>Algerian dinar (د.ج) — DZD</option>
		<option value="EGP" <?php selected( $currency, 'EGP' ); ?>>Egyptian pound (EGP) — EGP</option>
		<option value="ERN" <?php selected( $currency, 'ERN' ); ?>>Eritrean nakfa (Nfk) — ERN</option>
		<option value="ETB" <?php selected( $currency, 'ETB' ); ?>>Ethiopian birr (Br) — ETB</option>
		<option value="EUR" <?php selected( $currency, 'EUR' ); ?>>Euro (€) — EUR</option>
		<option value="FJD" <?php selected( $currency, 'FJD' ); ?>>Fijian dollar ($) — FJD</option>
		<option value="FKP" <?php selected( $currency, 'FKP' ); ?>>Falkland Islands pound (£) — FKP</option>
		<option value="GBP" <?php selected( $currency, 'GBP' ); ?>>Pound sterling (£) — GBP</option>
		<option value="GEL" <?php selected( $currency, 'GEL' ); ?>>Georgian lari (₾) — GEL</option>
		<option value="GGP" <?php selected( $currency, 'GGP' ); ?>>Guernsey pound (£) — GGP</option>
		<option value="GHS" <?php selected( $currency, 'GHS' ); ?>>Ghana cedi (₵) — GHS</option>
		<option value="GIP" <?php selected( $currency, 'GIP' ); ?>>Gibraltar pound (£) — GIP</option>
		<option value="GMD" <?php selected( $currency, 'GMD' ); ?>>Gambian dalasi (D) — GMD</option>
		<option value="GNF" <?php selected( $currency, 'GNF' ); ?>>Guinean franc (Fr) — GNF</option>
		<option value="GTQ" <?php selected( $currency, 'GTQ' ); ?>>Guatemalan quetzal (Q) — GTQ</option>
		<option value="GYD" <?php selected( $currency, 'GYD' ); ?>>Guyanese dollar ($) — GYD</option>
		<option value="HKD" <?php selected( $currency, 'HKD' ); ?>>Hong Kong dollar ($) — HKD</option>
		<option value="HNL" <?php selected( $currency, 'HNL' ); ?>>Honduran lempira (L) — HNL</option>
		<option value="HRK" <?php selected( $currency, 'HRK' ); ?>>Croatian kuna (kn) — HRK</option>
		<option value="HTG" <?php selected( $currency, 'HTG' ); ?>>Haitian gourde (G) — HTG</option>
		<option value="HUF" <?php selected( $currency, 'HUF' ); ?>>Hungarian forint (Ft) — HUF</option>
		<option value="IDR" <?php selected( $currency, 'IDR' ); ?>>Indonesian rupiah (Rp) — IDR</option>
		<option value="ILS" <?php selected( $currency, 'ILS' ); ?>>Israeli new shekel (₪) — ILS</option>
		<option value="IMP" <?php selected( $currency, 'IMP' ); ?>>Manx pound (£) — IMP</option>
		<option value="INR" <?php selected( $currency, 'INR' ); ?>>Indian rupee (₹) — INR</option>
		<option value="IQD" <?php selected( $currency, 'IQD' ); ?>>Iraqi dinar (د.ع) — IQD</option>
		<option value="IRR" <?php selected( $currency, 'IRR' ); ?>>Iranian rial (﷼) — IRR</option>
		<option value="IRT" <?php selected( $currency, 'IRT' ); ?>>Iranian toman (تومان) — IRT</option>
		<option value="ISK" <?php selected( $currency, 'ISK' ); ?>>Icelandic króna (kr.) — ISK</option>
		<option value="JEP" <?php selected( $currency, 'JEP' ); ?>>Jersey pound (£) — JEP</option>
		<option value="JMD" <?php selected( $currency, 'JMD' ); ?>>Jamaican dollar ($) — JMD</option>
		<option value="JOD" <?php selected( $currency, 'JOD' ); ?>>Jordanian dinar (د.ا) — JOD</option>
		<option value="JPY" <?php selected( $currency, 'JPY' ); ?>>Japanese yen (¥) — JPY</option>
		<option value="KES" <?php selected( $currency, 'KES' ); ?>>Kenyan shilling (KSh) — KES</option>
		<option value="KGS" <?php selected( $currency, 'KGS' ); ?>>Kyrgyzstani som (сом) — KGS</option>
		<option value="KHR" <?php selected( $currency, 'KHR' ); ?>>Cambodian riel (៛) — KHR</option>
		<option value="KMF" <?php selected( $currency, 'KMF' ); ?>>Comorian franc (Fr) — KMF</option>
		<option value="KPW" <?php selected( $currency, 'KPW' ); ?>>North Korean won (₩) — KPW</option>
		<option value="KRW" <?php selected( $currency, 'KRW' ); ?>>South Korean won (₩) — KRW</option>
		<option value="KWD" <?php selected( $currency, 'KWD' ); ?>>Kuwaiti dinar (د.ك) — KWD</option>
		<option value="KYD" <?php selected( $currency, 'KYD' ); ?>>Cayman Islands dollar ($) — KYD</option>
		<option value="KZT" <?php selected( $currency, 'KZT' ); ?>>Kazakhstani tenge (₸) — KZT</option>
		<option value="LAK" <?php selected( $currency, 'LAK' ); ?>>Lao kip (₭) — LAK</option>
		<option value="LBP" <?php selected( $currency, 'LBP' ); ?>>Lebanese pound (ل.ل) — LBP</option>
		<option value="LKR" <?php selected( $currency, 'LKR' ); ?>>Sri Lankan rupee (රු) — LKR</option>
		<option value="LRD" <?php selected( $currency, 'LRD' ); ?>>Liberian dollar ($) — LRD</option>
		<option value="LSL" <?php selected( $currency, 'LSL' ); ?>>Lesotho loti (L) — LSL</option>
		<option value="LYD" <?php selected( $currency, 'LYD' ); ?>>Libyan dinar (د.ل) — LYD</option>
		<option value="MAD" <?php selected( $currency, 'MAD' ); ?>>Moroccan dirham (د.م.) — MAD</option>
		<option value="MDL" <?php selected( $currency, 'MDL' ); ?>>Moldovan leu (MDL) — MDL</option>
		<option value="MGA" <?php selected( $currency, 'MGA' ); ?>>Malagasy ariary (Ar) — MGA</option>
		<option value="MKD" <?php selected( $currency, 'MKD' ); ?>>Macedonian denar (ден) — MKD</option>
		<option value="MMK" <?php selected( $currency, 'MMK' ); ?>>Burmese kyat (Ks) — MMK</option>
		<option value="MNT" <?php selected( $currency, 'MNT' ); ?>>Mongolian tögrög (₮) — MNT</option>
		<option value="MOP" <?php selected( $currency, 'MOP' ); ?>>Macanese pataca (P) — MOP</option>
		<option value="MRU" <?php selected( $currency, 'MRU' ); ?>>Mauritanian ouguiya (UM) — MRU</option>
		<option value="MUR" <?php selected( $currency, 'MUR' ); ?>>Mauritian rupee (₨) — MUR</option>
		<option value="MVR" <?php selected( $currency, 'MVR' ); ?>>Maldivian rufiyaa (.ރ) — MVR</option>
		<option value="MWK" <?php selected( $currency, 'MWK' ); ?>>Malawian kwacha (MK) — MWK</option>
		<option value="MXN" <?php selected( $currency, 'MXN' ); ?>>Mexican peso ($) — MXN</option>
		<option value="MYR" <?php selected( $currency, 'MYR' ); ?>>Malaysian ringgit (RM) — MYR</option>
		<option value="MZN" <?php selected( $currency, 'MZN' ); ?>>Mozambican metical (MT) — MZN</option>
		<option value="NAD" <?php selected( $currency, 'NAD' ); ?>>Namibian dollar (N$) — NAD</option>
		<option value="NGN" <?php selected( $currency, 'NGN' ); ?>>Nigerian naira (₦) — NGN</option>
		<option value="NIO" <?php selected( $currency, 'NIO' ); ?>>Nicaraguan córdoba (C$) — NIO</option>
		<option value="NOK" <?php selected( $currency, 'NOK' ); ?>>Norwegian krone (kr) — NOK</option>
		<option value="NPR" <?php selected( $currency, 'NPR' ); ?>>Nepalese rupee (₨) — NPR</option>
		<option value="NZD" <?php selected( $currency, 'NZD' ); ?>>New Zealand dollar ($) — NZD</option>
		<option value="OMR" <?php selected( $currency, 'OMR' ); ?>>Omani rial (ر.ع.) — OMR</option>
		<option value="PAB" <?php selected( $currency, 'PAB' ); ?>>Panamanian balboa (B/.) — PAB</option>
		<option value="PEN" <?php selected( $currency, 'PEN' ); ?>>Sol (S/) — PEN</option>
		<option value="PGK" <?php selected( $currency, 'PGK' ); ?>>Papua New Guinean kina (K) — PGK</option>
		<option value="PHP" <?php selected( $currency, 'PHP' ); ?>>Philippine peso (₱) — PHP</option>
		<option value="PKR" <?php selected( $currency, 'PKR' ); ?>>Pakistani rupee (₨) — PKR</option>
		<option value="PLN" <?php selected( $currency, 'PLN' ); ?>>Polish złoty (zł) — PLN</option>
		<option value="PRB" <?php selected( $currency, 'PRB' ); ?>>Transnistrian ruble (р.) — PRB</option>
		<option value="PYG" <?php selected( $currency, 'PYG' ); ?>>Paraguayan guaraní (₲) — PYG</option>
		<option value="QAR" <?php selected( $currency, 'QAR' ); ?>>Qatari riyal (ر.ق) — QAR</option>
		<option value="RON" <?php selected( $currency, 'RON' ); ?>>Romanian leu (lei) — RON</option>
		<option value="RSD" <?php selected( $currency, 'RSD' ); ?>>Serbian dinar (рсд) — RSD</option>
		<option value="RUB" <?php selected( $currency, 'RUB' ); ?>>Russian ruble (₽) — RUB</option>
		<option value="RWF" <?php selected( $currency, 'RWF' ); ?>>Rwandan franc (Fr) — RWF</option>
		<option value="SAR" <?php selected( $currency, 'SAR' ); ?>>Saudi riyal (ر.س) — SAR</option>
		<option value="SBD" <?php selected( $currency, 'SBD' ); ?>>Solomon Islands dollar ($) — SBD</option>
		<option value="SCR" <?php selected( $currency, 'SCR' ); ?>>Seychellois rupee (₨) — SCR</option>
		<option value="SDG" <?php selected( $currency, 'SDG' ); ?>>Sudanese pound (ج.س.) — SDG</option>
		<option value="SEK" <?php selected( $currency, 'SEK' ); ?>>Swedish krona (kr) — SEK</option>
		<option value="SGD" <?php selected( $currency, 'SGD' ); ?>>Singapore dollar ($) — SGD</option>
		<option value="SHP" <?php selected( $currency, 'SHP' ); ?>>Saint Helena pound (£) — SHP</option>
		<option value="SLL" <?php selected( $currency, 'SLL' ); ?>>Sierra Leonean leone (Le) — SLL</option>
		<option value="SOS" <?php selected( $currency, 'SOS' ); ?>>Somali shilling (Sh) — SOS</option>
		<option value="SRD" <?php selected( $currency, 'SRD' ); ?>>Surinamese dollar ($) — SRD</option>
		<option value="SSP" <?php selected( $currency, 'SSP' ); ?>>South Sudanese pound (£) — SSP</option>
		<option value="STN" <?php selected( $currency, 'STN' ); ?>>São Tomé and Príncipe dobra (Db) — STN</option>
		<option value="SYP" <?php selected( $currency, 'SYP' ); ?>>Syrian pound (ل.س) — SYP</option>
		<option value="SZL" <?php selected( $currency, 'SZL' ); ?>>Swazi lilangeni (E) — SZL</option>
		<option value="THB" <?php selected( $currency, 'THB' ); ?>>Thai baht (฿) — THB</option>
		<option value="TJS" <?php selected( $currency, 'TJS' ); ?>>Tajikistani somoni (ЅМ) — TJS</option>
		<option value="TMT" <?php selected( $currency, 'TMT' ); ?>>Turkmenistan manat (m) — TMT</option>
		<option value="TND" <?php selected( $currency, 'TND' ); ?>>Tunisian dinar (د.ت) — TND</option>
		<option value="TOP" <?php selected( $currency, 'TOP' ); ?>>Tongan paʻanga (T$) — TOP</option>
		<option value="TRY" <?php selected( $currency, 'TRY' ); ?>>Turkish lira (₺) — TRY</option>
		<option value="TTD" <?php selected( $currency, 'TTD' ); ?>>Trinidad and Tobago dollar ($) — TTD</option>
		<option value="TWD" <?php selected( $currency, 'TWD' ); ?>>New Taiwan dollar (NT$) — TWD</option>
		<option value="TZS" <?php selected( $currency, 'TZS' ); ?>>Tanzanian shilling (Sh) — TZS</option>
		<option value="UAH" <?php selected( $currency, 'UAH' ); ?>>Ukrainian hryvnia (₴) — UAH</option>
		<option value="UGX" <?php selected( $currency, 'UGX' ); ?>>Ugandan shilling (UGX) — UGX</option>
		<option value="USD" <?php selected( $currency, 'USD' ); ?>>United States (US) dollar ($) — USD</option>
		<option value="UYU" <?php selected( $currency, 'UYU' ); ?>>Uruguayan peso ($) — UYU</option>
		<option value="UZS" <?php selected( $currency, 'UZS' ); ?>>Uzbekistani som (UZS) — UZS</option>
		<option value="VEF" <?php selected( $currency, 'VEF' ); ?>>Venezuelan bolívar (2008–2018) (Bs F) — VEF</option>
		<option value="VES" <?php selected( $currency, 'VES' ); ?>>Venezuelan bolívar (Bs.) — VES</option>
		<option value="VND" <?php selected( $currency, 'VND' ); ?>>Vietnamese đồng (₫) — VND</option>
		<option value="VUV" <?php selected( $currency, 'VUV' ); ?>>Vanuatu vatu (Vt) — VUV</option>
		<option value="WST" <?php selected( $currency, 'WST' ); ?>>Samoan tālā (T) — WST</option>
		<option value="XAF" <?php selected( $currency, 'XAF' ); ?>>Central African CFA franc (CFA) — XAF</option>
		<option value="XCD" <?php selected( $currency, 'XCD' ); ?>>East Caribbean dollar ($) — XCD</option>
		<option value="XOF" <?php selected( $currency, 'XOF' ); ?>>West African CFA franc (CFA) — XOF</option>
		<option value="XPF" <?php selected( $currency, 'XPF' ); ?>>CFP franc (XPF) — XPF</option>
		<option value="YER" <?php selected( $currency, 'YER' ); ?>>Yemeni rial (﷼) — YER</option>
		<option value="ZAR" <?php selected( $currency, 'ZAR' ); ?>>South African rand (R) — ZAR</option>
		<option value="ZMW" <?php selected( $currency, 'ZMW' ); ?>>Zambian kwacha (ZK) — ZMW</option>
</select>